[package]

name = "consul"
version = "0.3.0"
edition = "2018"
authors = ["Andrew Useckas <andrew.useckas@threat-x.com>", "Stu Small <stuart.small@threat-x.com>", "YoungKing <yanckin@gmail.com>"]
description = "Rust client libray for Consul HTTP API"
documentation = "https://docs.rs/consul/"
repository = "https://github.com/stusmall/consul-rust"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["consul", "discovery"]



[dependencies]
base64 = "0.12.1"
error-chain = "0.12"
serde = "1"
serde_derive = "1"
serde_json = "1.0"
rand = "0.7.3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
url = "2.1"
