[package]

name = "consul"
version = "0.2.0"
authors = ["Andrew Useckas <andrew.useckas@threat-x.com>", "Stu Small <stuart.small@threat-x.com>", "YoungKing <yanckin@gmail.com>"]
description = "Rust client libray for Consul HTTP API"
documentation = "https://docs.rs/consul/"
repository = "https://github.com/stusmall/consul-rust"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["consul", "discovery"]

exclude = [
    "data/*",
]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
hyper = "0.10"
hyper-openssl = "0.2"
openssl = "0.9"
