[package]

name = "consul"
version = "0.3.0"
authors = ["Andrew Useckas <andrew.useckas@threat-x.com>", "Stu Small <stuart.small@threat-x.com>", "YoungKing <yanckin@gmail.com>"]
description = "Rust client libray for Consul HTTP API"
documentation = "https://docs.rs/consul/"
repository = "https://github.com/stusmall/consul-rust"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["consul", "discovery"]



[dependencies]
base64 = "0.10"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
reqwest = {version="0.9", features=["default-tls"]}
